mrstModule add ad-core ad-props ad-blackoil
mrstModule add test-suite
mrstModule add ensemble
mrstModule add mrst-gui
mrstModule add network-models
mrstModule add upr

%% Set up SAIGUP case

saigup = TestCase('saigup_wo');
saigup.state0.s = saigup.state0.s.*0 + [0,1];

problem = saigup.getPackedSimulationProblem();
%clearPackedSimulatorOutput(problem)
simulatePackedProblem(problem);

[wellSolsFine, statesFine] = getPackedSimulatorOutput(problem);

%% Need a 2D model to construct graph. Each well should only have one cell
cProblem.SimulatorSetup = coarsenSetup(problem.SimulatorSetup, [25 25 1]);

%% Set up TriNet model
trinet = TriNet(cProblem.SimulatorSetup.model, ...
                cProblem.SimulatorSetup.schedule, ...
                cProblem.SimulatorSetup.state0);

%% Set up parameters and objective function

problem = trinet.getPackedSimulationProblem();
samples = struct('problem', {{problem}}, ...
                 'num',     1);

config = {
    ...%name      include   scaling  boxlims lumping subset relativeLimits  mapTo
    'porevolume',       1, 'linear',   [],     [],    [],     [0.01 10],   'node' 
    'conntrans',        1, 'log',      [],     [],    [],     [0.01 100],  'well'
    'transmissibility', 1, 'log'       [],     [],    [],     [0.01 100],  'edge'}; 

params = [];
for k = 1:size(config,1)
    if config{k, 2} == 0, continue, end     % include = 0
    params = addNetworkModelParameter(params, problem.SimulatorSetup, ...
        'name',    config{k,1}, 'scaling', config{k,3}, ...
        'boxLims', config{k,4}, 'lumping', config{k,5}, ...
        'subset',  config{k,6}, 'relativeLimits',config{k,7}, ...
        'uniformLimits', false);
end

% Define objective function
weighting = objectiveWeighting(wellSolsFine);

objFun = @(model, states, schedule, varargin) ...
    matchObservedOW(model, states, schedule, statesFine, varargin{:}, ...
                    weighting{:}, 'mismatchSum', false);

trinet.params = params;

%% Triangle refinement

p0 = OptimizationProblem(samples, ...
            'parameters',       params, ...
            'name', 'saigup_trinet_ref', ...
            'objective',        objFun, ...
            'setupType',  'simulation', ...
            'verboseSimulation', false, ...
            'solverFunOptions',  {'scalarObjective', false});

[trinet, p, h] = optimizeNetworkModelTopology(trinet, p0, config, ...
                'refineFrom', 'triangles', 'selectWith', 'fraction', ...
                'maxFrac', 0.10, 'sensMap', 'mean', ...
                'maxIt', 200, 'outerMaxIt', 20, 'totalMaxIt', 1000, ...
                'outerObjTol', 1e-4, 'resTolAbs', 1e-9, ...
                'name', "TriNet (dynamic)", 'resChangeTolRel', 0.01);

%% Static tuning

p0 = OptimizationProblem(samples, ...
            'parameters',       params, ...
            'name', 'saigup_trinet_static', ...
            'objective',        objFun, ...
            'setupType',  'simulation', ...
            'verboseSimulation', false, ...
            'solverFunOptions',  {'scalarObjective', false});

[trinet, p, h] = optimizeNetworkModel(trinet, p0, 'maxIt', 40);
